// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCYsym0ndB2wc3-XUUcaHV6lG01H1v2a5I',
    appId: '1:572478246082:web:b318df50acba64e2b77f5b',
    messagingSenderId: '572478246082',
    projectId: 'mypatient-5b9ac',
    authDomain: 'mypatient-5b9ac.firebaseapp.com',
    databaseURL: 'https://mypatient-5b9ac-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'mypatient-5b9ac.firebasestorage.app',
    measurementId: 'G-J9MQ5KWH12',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB4XZdh5p9VIzdVOc9BKzYGvFicJd532Fw',
    appId: '1:572478246082:android:ab76739edb213525b77f5b',
    messagingSenderId: '572478246082',
    projectId: 'mypatient-5b9ac',
    databaseURL: 'https://mypatient-5b9ac-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'mypatient-5b9ac.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCLPWtsUpbAMUD-XmYZeYV-C0SEuf1TjjA',
    appId: '1:572478246082:ios:55e4e551a7fe2da0b77f5b',
    messagingSenderId: '572478246082',
    projectId: 'mypatient-5b9ac',
    databaseURL: 'https://mypatient-5b9ac-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'mypatient-5b9ac.firebasestorage.app',
    iosBundleId: 'com.example.myPatients',
  );
}
